### ISSUE TITLE
[Feature] Add proper theming to Discord

### ISSUE THREAD

**Issue by NotZoeyDev** [enmity-mod/enmity#1]
Add a proper theming engine to Discord.

Work done so far:
- Injecting colours into the chat area
- Injecting theme into Discord

Work to be done:
- Apply the custom colours to the React Native UI part of Discord

Maybe:
- Allow to customize Discord's layout (Hooking createStyleSheet and createThemedStyleSheet)

**Comment by 01SOL** [comment]
How does one even add theme? Doesn't seem to add when links added

**Comment by NotZoeyDev** [comment]
Themes has been implemented in v1.0.7. Closing this issue.
