### ISSUE TITLE
[Feature] Export/import all plugins/themes

### ISSUE THREAD

**Issue by nouun** [enmity-mod/enmity#12]
The ability to export and import all of your current plugins and/or themes would be nice as after updating non-jailbroken I have to go through and reinstall all of my plugins and theme again.

**Comment by localipisapussy** [comment]
@localip https://files.catbox.moe/b991q2.mp4 help

**Comment by localip** [comment]
V2 is in a fix-only state as we work on V3. There are no plans to backport this to V2.
