### ISSUE TITLE
Problems with installing plugins/themes

### ISSUE THREAD

**Issue by ShatteredDisk** [enmity-mod/enmity#19]
Hello!
I'm having some problems with Enmity in terms of installing plugins and themes easily.

1: Using the "+" button in the themes and plugins list does not do anything after entering a URL linking to a file.

2: Using a store and clicking "Install plugin" results in a message along the lines of "Safari cannot open the page because the address is invalid." (This is probably because the app’s URI is messed up in some way)

I am using a Jailed iPad Generation 5 running iOS 15.1.
Enmity is installed via a free Apple Developer account.

Any help would be appriciated.
~ Thanks, ShatteredDisk

**Comment by ShatteredDisk** [comment]
UPDATE: Plugins/themes show up in the list when the JSON/JS files are added to the app's folder. Themes do not work as they get turned off after receiving and accepting the prompt to restart the app.

**Comment by localip** [comment]
Where did you get the IPA from?

**Comment by ShatteredDisk** [comment]
https://github.com/enmity-mod/tweak/releases/tag/release-v2.1.0

sorry for the late response

**Comment by ShatteredDisk** [comment]
I'm trying not to reach the free apple developer limit, but I'm going to reinstall Enmity in a few days

**Comment by ShatteredDisk** [comment]
Finally got around to installing the latest version and can confirm it is still indeed broken. Is there anything I can do at this point?
