### ISSUE TITLE
[Feature] Add a preferences API for plugins

### ISSUE THREAD

**Issue by NotZoeyDev** [enmity-mod/enmity#2]
Add a preferences API for plugins so users can set custom settings for their installed plugins.

Work to be done:
- Make a preferences API for plugins to fetch their currently set settings
- Automatically generate an UI for settings set by the plugin definition

**Comment by localip** [comment]
Custom Settings components is done.
Automatically generated settings are left to do.

**Comment by localip** [comment]
Plugin UIs are now controlled by developers, automatically generated UIs aren't necessary. 
Closing until further notice.

**Comment by charlie-sans** [comment]
why not jsut stre the settings to a config file then read when needed?

and yeah auto generated UIs are kinda crap, what happens if the dev wants to make there own?
