### ISSUE TITLE
[Bug] When I get pinged while I'm not using the enmity app I don't get notified.

### ISSUE THREAD

**Issue by PrimePlatypus** [enmity-mod/enmity#20]
Issue: I don't get any notifications when I get pinged outside of the enmity app. My notifications are on, and I am on an iPhone XR on iOS 16.0 beta 4. Something interesting that I noticed is that the enmity app didn't show up in the background refresh tab in settings.

Expected behavior: I expected that I would still get notifications when pinged even while I'm not using enmity.

**Comment by ServoAtya** [comment]
I have the same issue also im using a distribution certificate with my paid developer account, i should get notifications, and works with other apps.

**Comment by localipsmomismybitch** [comment]
> I have the same issue also im using a distribution certificate with my paid developer account, i should get notifications, and works with other apps.

https://files.catbox.moe/b991q2.mp4

**Comment by localip** [comment]
This is an apple limitation. You need a paid developer certificate (100$/y) to be able to sign an IPA with notifications. We cannot do anything about this.
