### ISSUE TITLE
I know this isn't the right place to contact for support but I couldn't find anywhere else

### ISSUE THREAD

**Issue by LowkeyTay** [enmity-mod/enmity#27]
I was banned on the discord server, for I don't know reasons I was wondering if you could unban that account so I could rejoin. My username was fr and I had a Roblox stitch face pfp. Please help.

**Comment by LowkeyTay** [comment]
Oh my account got hacked around 3:55 pm which was probably the reason why I got banned from the server..

**Comment by localip** [comment]
I’ve gone ahead and unbanned you.
