### ISSUE TITLE
Apple Watch support?

### ISSUE THREAD

**Issue by lachydaves25** [enmity-mod/enmity#30]
Will this client mod get Apple Watch Support. I don't know if it's really possible to do with the way you have to install it through the AltStore but if it is can it be done? Oh and also another quick feature to add a, announce notifications for DM's.

**Comment by FifiTheBulldog** [comment]
Enmity will almost certainly not support the Watch, unless Discord builds an Apple Watch app. Enmity is not a full third-party client; it can only modify Discord's own iOS app. This means that if Discord doesn't build an app for the Watch, then Enmity has no starting point to modify anything there.

**Comment by lachydaves25** [comment]
Ah ok got it
