### ISSUE TITLE
[Bug] App stuck on connecting

### ISSUE THREAD

**Issue by Lerbiq** [enmity-mod/enmity#68]
## Issue Description

**Summary:**
The app gets stuck on connecting sometimes when opening. It's more likely to happen if the app is closed completely.

**Expected Behavior:**
App opens and connects within moments.

**Current Behavior:**
App opens and gets stuck at "Connecting..." for somewhere between 1-3 minutes. Instead of waiting it out going to the account switcher for a moment one or two times makes the app connect successfully.

## Reproduction Steps

1. Close the app completely.
2. Open the app again.
3. Most of the times it will get stuck at connecting.

## Screenshots / Videos
https://imgur.com/a/LDMMzz0

## Environment

- **iOS Version:** iOS 17 Developer Beta 3
- **Device:** iPhone XS
- **Enmity:** 06af72c
- **Discord:** 184.0
- **Tweak:** 2.2.6 (Regular)
- **Bytecode:** 89
- **Hermes:** for RN 0.70.6

**Comment by mak448a** [comment]
You are actually connected, even though it says connecting. It's slightly annoying.

**Comment by localip** [comment]
Please refer to https://github.com/enmity-mod/tweak/issues/28 for a fix.

**Comment by mak448a** [comment]
Already found this. Thank you!
