### ISSUE TITLE
[Bug] Voice messages cause a crash

### ISSUE THREAD

**Issue by Lerbiq** [enmity-mod/enmity#69]
## Issue Description

**Summary:**
Enmity crashes completely when it loads a voice message.

**Expected Behavior:**
App loads voice messages without issues and allows you to play them.

**Current Behavior:**
Enmity crashes completely whenever it loads a voice message. This can cause you to crash every time you open the app. Currently only way to mitigate the crash is using a `FixVoiceMessageCrash` plugin, but that only turns them into file attachment and doesn't allow you to play them in-app.

## Reproduction Steps

1. Send a voice message in either a DM or a text channel.
2. Close the app.
3. Open the app again.
4. App will crash.

## Screenshots / Videos
https://imgur.com/gallery/qineFpY

## Environment

- **iOS Version:** iOS 17 Developer Beta 3
- **Device:** iPhone XS
- **Enmity:** 06af72c
- **Discord:** 184.0
- **Tweak:** 2.2.6 (Regular)
- **Bytecode:** 89
- **Hermes:** for RN 0.70.6

**Comment by YangTheParrot** [comment]
can you confirm if your device locale (language) is on english? because it might have something to do with it. when i set my device to english, nothing crashes and everything works fine but when i set it to french, it starts crashing.

**Comment by Lerbiq** [comment]
> can you confirm if your device locale (language) is on english? because it might have something to do with it. when i set my device to english, nothing crashes and everything works fine but when i set it to french, it starts crashing. 

My device locale was set to Czech. After switching it to English voice messages work fine.

Based on the conversations in the Discord server and this one I suspect this issue only appears with non-English locales.

**Comment by localip** [comment]
Is this still the case? I will be closing this issue as I believe this was a stock Discord issue. If this issue is still present, reply here and I will re-open this issue.
