### ISSUE TITLE
[Bug] New message bar at top of screen is in UTC

### ISSUE THREAD

**Issue by SomeAspy** [enmity-mod/enmity#7]
Issue: the time is incorrect on the message bar, it is in UTC instead of the devices time zone. 

Expected behavior: the new message bar should abide to the devices local time
![image](https://user-images.githubusercontent.com/33640860/163627666-3a55edf3-636a-4b94-a5d5-bb8b025cfb54.png)

**Comment by localip** [comment]
How about now?

**Comment by SomeAspy** [comment]
still happens on the latest ipa

**Comment by Kodey-Kayla** [comment]
Can confirm still happening on latest as of now. (Ver f047a56)

**Comment by SomeAspy** [comment]
Abandoned issue? @colin273 cannot replicate.
