### ISSUE TITLE
AltStore install error

### ISSUE THREAD

**Issue by Yerthesweat** [enmity-mod/enmity#73]
When attempting to install enmity via AltStore using the ipa 
This error comes up

create_directories: The filename or extension is too long.: "C:\Users\ADMINI~1\AppData\Local\Temp\f83c1551-14e0-4440-b3c1-83d94ab752c8\Payload\App.app\assets\_node_modules\.pnpm\@react-navigation+elements@1.3.18_patch_hash=tm3j4nw5qxof2dxeh46s5mokpa_@react-navigation+nat_eqnm6ustzf2c5ljdvmfr6cc724\node_modules\"

**Comment by huaraina** [comment]
if i recall correctly the solution is using 7zip to open the ipa, going through the directory, copying the folder name (very important), then renaming the folder, and then going into the manifest.json file and replace all instances (i think around 4) of the old name with the new name.

**Comment by localip** [comment]
Please try with the new AltStore repository: https://enmity-mod.github.io/repo/
