### ISSUE TITLE
[bug] enmity crashes every time i open it

### ISSUE THREAD

**Issue by Lunatic-T** [enmity-mod/enmity#76]
its crashing when i install a plugin that has errors, please make it crash proof and try making it remove the plugin from itself if it errors on install (or when opening the app) i would love to see this. i cant live with crashing every time and having to reinstall everything. thanks!

**Comment by codingnooob** [comment]
Same, installed and enabled a theme from the Enmity discord channel and now it crashes every time. Worst of all, it happens even after reinstalling it :/

**Comment by codingnooob** [comment]
Similar to #25

**Comment by localip** [comment]
This can be due to faulty plugins/themes. This annoyance was addressed in V3 with several mitigations. I do not plan to backport this to V2 myself. V2 is now solely maintained by @colin273.
