### ISSUE TITLE
FALSELY BANNED IN COMMUNICATIONS SERVER

### ISSUE THREAD

**Issue by launcers30q** [enmity-mod/enmity#88]
I got muted for one hour for the reason “Roblox developer” after that I got banned, I used an alt account to contact the staff members and they immediately banned me falsely again, please do something my discord is “launcers30q”

**Comment by catnipjson** [comment]
haha ok lol

**Comment by Skawtnyc** [comment]
It wasn’t falsely. You really were banned. Twice.

**Comment by uchks** [comment]
Hello [launcers30q](https://github.com/launcers30q),

I muted you for your persistent social ineptitude. Your incessant chatter and uncourteous behavior towards other servers are unacceptable.

Despite being reprimanded, you continued to engage in inappropriate behavior by spamming messages to two staff members, Bryan and me. This behavior demonstrates a lack of respect. I strongly advise you to reconsider your life choices and make positive changes in your behavior. Have a good day roblox developer.

**Comment by catnipjson** [comment]
i got muted for one hour for reason roblox developer

**Comment by SerStars** [comment]
> I got muted for one hour for the reason “Roblox developer”
You already got verbally warned before your mute.
> after that I got banned, I used an alt account to contact the staff members and they immediately banned me falsely again
That wasn't a false ban, you joined with your alt account even tho you got banned.
Ban reason: ban evasion
> please do something my discord is “launcers30q”
https://github.com/enmity-mod/enmity/issues/88#issuecomment-2369336859

**Comment by catnipjson** [comment]
![image](https://github.com/user-attachments/assets/a260b13c-520b-4081-ad46-17d30c2ffc06)

**Comment by SerStars** [comment]
Someone actually close this thing lol

**Comment by catnipjson** [comment]
no i wanna see him reply

**Comment by colin273** [comment]
Pro tip for OP: being annoying and stupid, then attempting to deny responsibility for your own behavior and everyone's annoyance at it, is spoiled 8-year-old behavior. (Underage users are not allowed on Discord at all, just in case you weren't aware.) That was why you got banned, though putting "Roblox developer" in your profile certainly doesn't make anyone over the age of 12 think more of your maturity level.
