### ISSUE TITLE
[Feature] Support for android

### ISSUE THREAD

**Issue by pikokr** [enmity-mod/enmity#9]
Discord android alpha build now runs with react native.

So how about making enmity runs with both android and ios?

**Comment by IamNickerson** [comment]
USE ALIUCORD https://github.com/Aliucord/Aliucord WHY TF YOU NEED ENMITY IN ANDRIOD WHILE THERE IS ALREADY MOD FOR ANDRIOD CALLED ALIUCORD

**Comment by IamNickerson** [comment]
No only ios

**Comment by pikokr** [comment]
It's now available in discord android beta version

**Comment by IamNickerson** [comment]
...

**Comment by IamNickerson** [comment]
How can you know?

**Comment by nikosszzz** [comment]
is this something can could happen? the RN version is out on stable in the play store.

**Comment by IamNickerson** [comment]
I have no clue my guy these people said they made one for Android but i don't see it in github

**Comment by nikosszzz** [comment]
> I have no clue my guy these people said they made one for Android but i don't see it in github

Well I never saw any official Enmity staff say they actually did **make a Android version of it**.

I have only seen an attempt by someone else but never got public for everyone else to use. That means a official and publicly released version of Enmity for Android doesn't exist, **atleast yet**.

**Comment by ItzOnlyAnimal** [comment]
lol

**Comment by Bettlee** [comment]
[Aliucord](https://github.com/Aliucord/Aliucord) made for Android

**Comment by leap0x7b** [comment]
Not helpful, also the RN version is still very WIP

**Comment by Bettlee** [comment]
> Not helpful, also the RN version is still very WIP

It's better than not having nothing else at all. If you click my link and read you may find some useful information

**Comment by localip** [comment]
V3 will feature Android support. There are no plans to bring this to V2.
